# Generated by Django 3.0.4 on 2020-04-11 03:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='address',
            field=models.CharField(max_length=96, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='experiences',
            field=models.CharField(max_length=32, verbose_name='Experiences'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='experiences_proofs',
            field=models.ImageField(upload_to='account/proof/%Y%m%d', verbose_name='Experiences Proofs'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='ktp',
            field=models.ImageField(upload_to='account/ktp/%Y%m%d', verbose_name='Identification ID (KTP/SIM/Student Card)'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='occupation',
            field=models.CharField(max_length=32, verbose_name='Occupation'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must start with 0. Up to 13 digits allowed.', regex='0[\\d]{9,12}')], verbose_name='Phone Number'),
        ),
        migrations.CreateModel(
            name='UserAppraisal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Rating')),
                ('feedback', models.TextField(blank=True, verbose_name='Feedback')),
                ('source_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisal_source_user', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisal_target_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('target_user', 'source_user')},
            },
        ),
    ]
