# Generated by Django 3.0.4 on 2020-04-06 14:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=96)),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must start with 0. Up to 13 digits allowed.', regex='0[\\d]{9,12}')])),
                ('ktp', models.ImageField(upload_to='account/ktp/%Y%m%d')),
                ('occupation', models.CharField(blank=True, max_length=32)),
                ('experiences', models.CharField(blank=True, max_length=32)),
                ('experiences_proofs', models.ImageField(blank=True, upload_to='account/proof/%Y%m%d')),
            ],
        ),
    ]
