# Generated by Django 3.0.4 on 2020-04-10 05:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200409_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAppraisal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five')], default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Rating')),
                ('feedback', models.TextField(blank=True, verbose_name='Feedback')),
                ('source_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisal_source_user', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisal_target_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('target_user', 'source_user')},
            },
        ),
    ]
