# Generated by Django 3.0.4 on 2020-04-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200411_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='userappraisal',
            name='date',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
    ]
