# Generated by Django 3.0.4 on 2020-04-12 11:10

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200412_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='cv',
            field=models.FileField(help_text='Only accepts pdfs', upload_to='account/document/cv/%Y%m%d', validators=[account.models.validate_file_extension], verbose_name='CV'),
        ),
    ]
