# Generated by Django 3.0.4 on 2020-04-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200412_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='about',
            field=models.CharField(blank=True, max_length=1024, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='account/photos/%Y%m%d', verbose_name='Photos'),
        ),
    ]
