# Generated by Django 3.0.4 on 2020-04-10 15:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True, verbose_name='Name')),
                ('description', models.CharField(max_length=96, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.IntegerField(blank=True, default=0, verbose_name='Fee')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.Course', verbose_name='Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_student', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_teacher', to=settings.AUTH_USER_MODEL, verbose_name='Teacher')),
            ],
            options={
                'unique_together': {('teacher', 'student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='TeacherPortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Score')),
                ('gpa_type', models.CharField(choices=[('W', 'Weighted'), ('UW', 'Unweighted')], help_text='Maximum GPA 4.0 for "Weighted", and 5.0 for "Unweighted"', max_length=2, verbose_name='GPA Type')),
                ('course', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.Course', verbose_name='Course')),
                ('teacher', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Teacher')),
            ],
            options={
                'unique_together': {('teacher', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], default='Monday', max_length=3, verbose_name='Day of Week')),
                ('time', models.TimeField(verbose_name='Time')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.Lesson', verbose_name='Lesson')),
            ],
            options={
                'unique_together': {('lesson', 'day_of_week', 'time')},
            },
        ),
    ]
