# Generated by Django 3.0.4 on 2020-04-15 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_cancelled',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is Cancelled'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='time_end',
            field=models.DateTimeField(null=True, verbose_name='Time End'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='time_start',
            field=models.DateTimeField(null=True, verbose_name='Time Start'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('teacher', 'time_start')},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='time',
        ),
    ]
