# Generated by Django 3.0.4 on 2020-04-11 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherportfolio',
            name='proof',
            field=models.ImageField(default='', upload_to='learning/teacher/proof/%Y%m%d', verbose_name='Experiences Proofs'),
        ),
        migrations.AlterField(
            model_name='teacherportfolio',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.Course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='teacherportfolio',
            name='gpa_type',
            field=models.CharField(choices=[('W', 'Weighted'), ('UW', 'Unweighted')], default='UW', help_text='Maximum GPA 4.0 for "Weighted", and 5.0 for "Unweighted"', max_length=2, verbose_name='GPA Type'),
        ),
        migrations.AlterField(
            model_name='teacherportfolio',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Teacher'),
        ),
    ]
