# Generated by Django 3.0.4 on 2020-04-12 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_auto_20200411_1218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherPortfolio',
        ),
    ]
