# Generated by Django 3.0.4 on 2020-04-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_auto_20200417_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_active',
        ),
        migrations.AddField(
            model_name='booking',
            name='proof',
            field=models.ImageField(null=True, upload_to='learning/booking/proof/%Y/%m/%d/', verbose_name='Transfer Proof'),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected'), ('C', 'Cancelled')], default='P', max_length=1, verbose_name='Status'),
        ),
    ]
