# Generated by Django 3.0.4 on 2020-04-12 11:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0003_delete_teacherportfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAppraisal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Rating')),
                ('feedback', models.TextField(blank=True, verbose_name='Feedback')),
                ('date', models.DateField(null=True, verbose_name='Date')),
                ('source_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisal_source_user', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisal_target_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('target_user', 'source_user')},
            },
        ),
        migrations.CreateModel(
            name='TeacherPortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Score')),
                ('gpa_type', models.CharField(choices=[('W', 'Weighted'), ('UW', 'Unweighted')], default='UW', help_text='Maximum GPA 4.0 for "Weighted", and 5.0 for "Unweighted"', max_length=2, verbose_name='GPA Type')),
                ('proof', models.ImageField(default='', upload_to='learning/teacher/proof/%Y%m%d', verbose_name='Experiences Proofs')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.Course', verbose_name='Course')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Teacher')),
            ],
            options={
                'unique_together': {('teacher', 'course')},
            },
        ),
    ]
